CREATE TABLE CANDLESTICKDATA (
  EXCHANGE VARCHAR(60) NOT NULL,
  TYPE VARCHAR(60) NOT NULL,
  NAME VARCHAR(60) NOT NULL,
  DURATION VARCHAR(60) NOT NULL,
  OPENTIME BIGINT(20) NOT NULL,
  CLOSETIME BIGINT(20) NOT NULL,
  OPEN FLOAT NOT NULL,
  CLOSE FLOAT NOT NULL,
  HIGH FLOAT NOT NULL,
  LOW FLOAT NOT NULL,
  VOLUME FLOAT NOT NULL,
  OPENTIMEUTC VARCHAR(60) NOT NULL,
  CLOSETIMEUTC VARCHAR(60) NOT NULL,
  CREATEDTIME VARCHAR(60) NOT NULL,
  EMA7 FLOAT,
  EMA9 FLOAT);


CREATE TABLE TRADEDATA (
  exchange VARCHAR(60) NOT NULL,
  type VARCHAR(60) NOT NULL,
  name VARCHAR(60) NOT NULL,
  currentprice FLOAT NOT NULL,
  totalbuyers FLOAT NOT NULL,
  totalsellers FLOAT NOT NULL,
  frontlinebuyers FLOAT NOT NULL,
  frontlinesellers FLOAT NOT NULL,
  totalordersexecuted FLOAT NOT NULL,
  makersorders FLOAT NOT NULL,
  bestmatch FLOAT NOT NULL,
  createdat VARCHAR(60) NOT NULL);